#include "./BaseUpgrade.zsc"
#include "./Dot.zsc"
#include "./ElementalUpgrade.zsc"
#include "./Registry.zsc"
#include "./UpgradeBag.zsc"

#include "./melee/DarkHarvest.zsc"
#include "./melee/Shield.zsc"
#include "./melee/Swiftness.zsc"

#include "./Explosive.zsc"
#include "./ExplosiveDeath.zsc"
#include "./Fragmentation.zsc"
#include "./HomingShots.zsc"
#include "./Indestructable.zsc"
#include "./Intuition.zsc"
#include "./Juggler.zsc"
#include "./Leech.zsc"
#include "./RapidFire.zsc"
#include "./Simpleupgrades.zsc"
#include "./Submunitions.zsc"
#include "./Thorns.zsc"

#include "./Fire.zsc"
#include "./Poison.zsc"
#include "./Acid.zsc"
#include "./Lightning.zsc"
#include "./ElementalSynthesis.zsc"
