#include "./BaseUpgrade.zs"
#include "./Dot.zs"
#include "./ElementalUpgrade.zs"
#include "./Registry.zs"
#include "./UpgradeBag.zs"

#include "./Explosive.zs"
#include "./ExplosiveDeath.zs"
#include "./Fragmentation.zs"
#include "./HomingShots.zs"
#include "./Indestructable.zs"
#include "./Intuition.zs"
#include "./Juggler.zs"
#include "./Leech.zs"
#include "./Melee.zs"
#include "./RapidFire.zs"
#include "./Simpleupgrades.zs"
#include "./Submunitions.zs"
#include "./Thorns.zs"

#include "./Fire.zs"
#include "./Poison.zs"
#include "./Acid.zs"
#include "./Lightning.zs"
#include "./ElementalSynthesis.zs"
