#include "./menu/main.zsc"
#include "./upgrades/main.zsc"

#include "./debug.zsc"
#include "./hud.zsc"
#include "./settings.zsc"

#include "./EventHandler.zsc"
#include "./LegendoomEffectGiver.zsc"
#include "./LegendoomUtil.zsc"
#include "./LegendoomWeaponInfo.zsc"
#include "./PerPlayerStats.zsc"
#include "./PlayerUpgradeGiver.zsc"
#include "./UpgradeGiver.zsc"
#include "./WeaponUpgradeGiver.zsc"
#include "./WeaponInfo.zsc"
