#include "./menu/main.zs"
#include "./upgrades/main.zs"

#include "./debug.zs"
#include "./hud.zs"
#include "./settings.zs"
#include "./RC.zs"

#include "./EventHandler.zs"
#include "./LegendoomEffectGiver.zs"
#include "./LegendoomUtil.zs"
#include "./LegendoomWeaponInfo.zs"
#include "./PerPlayerStats.zs"
#include "./PerPlayerStatsProxy.zs"
#include "./PlayerUpgradeGiver.zs"
#include "./UpgradeGiver.zs"
#include "./WeaponUpgradeGiver.zs"
#include "./WeaponInfo.zs"
#include "./WeaponTypeInference.zs"
