#include "./util.zsc"
#include "./settings.zsc"
#include "./LegendoomEffectGiver.zsc"
#include "./WeaponInfo.zsc"
#include "./PerPlayerStats.zsc"
#include "./EventHandler.zsc"
#include "./upgrades/main.zsc"
#include "./menu/main.zsc"
