// An inventory object that can't be dropped and you can only have one of.
// Name comes from Crossfire's force objects used to track spell effects and
// the like.
class TF_Force : Inventory {
  Default {
    Inventory.Amount 1;
    Inventory.MaxAmount 1;
    +INVENTORY.IGNORESKILL;
    +INVENTORY.UNTOSSABLE;
    +INVENTORY.UNDROPPABLE;
    +INVENTORY.QUIET;
  }
}

class TF_Util : Object {
  static string SafeTag(Actor obj) {
    if (obj) return obj.GetTag();
    return "null";
  }

  static string SafeClassName(Object obj) {
    if (obj) return obj.GetClassName();
    return "null";
  }

  static Inventory FindItemWithPrefix(Actor act, string prefix) {
    // GetClassName() isn't consistent about case, so lowercase everything before
    // we compare it to avoid, e.g., "LDPistolEffectActive" comparing different
    // to "ldpistolEffectActive".
    prefix = prefix.MakeLower();
    for (Inventory item = act.Inv; item; item = item.Inv) {
      string cls = item.GetClassName();
      cls = cls.MakeLower();
      if (cls.IndexOf(prefix) == 0) {
        return item;
      }
    }
    return null;
  }
}
