#!/usr/bin/env zsh
#
# Rebuild all of the logic files from scratch.
# This makes a bunch of assumptions about where the maps are stored that are only
# valid on my computer.

IWAD=chex3.wad tools/ap-scan "Chex Quest 3"
IWAD=doom.wad tools/ap-scan "Doom"
tools/ap-scan "Doom 2"
IWAD=freedoom1.wad tools/ap-scan "FreeDoom"
IWAD=freedoom2.wad tools/ap-scan "FreeDoom 2"
IWAD=heretic.wad tools/ap-scan "Heretic"
IWAD=plutonia.wad tools/ap-scan "Plutonia"
IWAD=tnt.wad tools/ap-scan "TNT"

tools/ap-scan "1000 Lines" "testdata/doom/maps/anthologies/2019 - 1000 Lines.zip"
tools/ap-scan "1000 Lines II" "testdata/doom/maps/anthologies/2020 - 1000 Lines 2.zip"
tools/ap-scan "Arrival" /ancilla/installs/games/PC/DOOM/maps/midiwads/2021\ -\ Arrival.zip
IWAD=doom.wad tools/ap-scan "Base Ganymede" /ancilla/installs/games/PC/DOOM/maps/megawads/2012\ -\ Base\ Ganymede\ \(doom1\).zip
IWAD=doom.wad MAPS="E1M1 E2M1 E3M1 E4M1" tools/ap-scan "Deathless" /ancilla/installs/games/PC/DOOM/maps/megawads/2018\ -\ Deathless.zip
tools/ap-scan "Demonfear" "testdata/doom/maps/megawads/2000 - Demonfear.zip"
tools/ap-scan "Eviternity" testdata/doom/maps/megawads/2019\ -\ Eviternity.zip
tools/ap-scan "Eviternity 2" testdata/doom/maps/megawads/2024\ -\ Eviternity\ 2.zip
IWAD=heretic.wad tools/ap-scan "Faithless" testdata/doom/maps/conversions/2024\ -\ Faithless\ Trilogy\ RC1a.pk3
tools/ap-scan "Going Down Turbo" "testdata/doom/maps/megawads/2025 - Going Down Turbo.zip"
tools/ap-scan "MAYhem 2048" "testdata/doom/maps/anthologies/2014 - MAYhem 2048.wad"
tools/ap-scan "Scientist" /ancilla/installs/games/PC/DOOM/maps/megawads/2023\ -\ Scientist\ 2023.zip
tools/ap-scan "Scythe" "testdata/doom/maps/megawads/2003 - Scythe.zip"
tools/ap-scan "Scythe 2" "testdata/doom/maps/megawads/2005 - Scythe 2.zip"
tools/ap-scan "Space Cats Saga" "testdata/doom/maps/conversions/2024 - Space Cats Saga 1.41.wad"
tools/ap-scan "The Adventures of Square" "testdata/doom/maps/conversions/2018 - The Adventures of Square 1+2.pk3"
tools/ap-scan "Zone 300" "testdata/doom/maps/megawads/2013 - Zone 300.zip"

# Maybe later
# IWAD=doom_fusion.ipk3 MAPS="E1M1 E2M1 E3M1 E4M1 MAP01 TN_MAP01 PL_MAP01" tools/ap-scan "WadFusion"
# tools/ap-scan "Necromantic Thirst" testdata/doom/maps/megawads/2024\ -\ Necromantic\ Thirst\ RC2.zip
# tools/ap-scan "Doom 2 In City Only" testdata/doom/maps/anthologies/2024\ -\ Doom\ 2\ In\ City\ Only.zip
