#!/usr/bin/env zsh
#
# Rebuild all of the logic files from scratch.
# This makes a bunch of assumptions about where the maps are stored that are only
# valid on my computer.

IWAD=doom.wad MAPS="E1M1 E2M1 E3M1 E4M1" tools/ap-scan "Doom"
tools/ap-scan "Doom 2"
IWAD=plutonia.wad tools/ap-scan "Plutonia"
IWAD=tnt.wad tools/ap-scan "TNT"
IWAD=freedoom1.wad MAPS="E1M1 E2M1 E3M1 E4M1" tools/ap-scan "FreeDoom"
IWAD=freedoom2.wad tools/ap-scan "FreeDoom 2"
IWAD=heretic.wad MAPS="E1M1 E2M1 E3M1 E4M1 E5M1" tools/ap-scan "Heretic"
IWAD=chex3.wad MAPS="E1M1 E2M1 E3M1" tools/ap-scan "Chex Quest 3"

tools/ap-scan "Demonfear" "testdata/doom/maps/megawads/2000 - Demonfear.zip"
tools/ap-scan "Scythe" "testdata/doom/maps/megawads/2003 - Scythe.zip"
tools/ap-scan "MAYhem 2048" "testdata/doom/maps/anthologies/2014 - MAYhem 2048.wad"
tools/ap-scan "Going Down Turbo" "testdata/doom/maps/megawads/2024 - Going Down Turbo [RC1-7].wad"
tools/ap-scan "1000 Lines" "testdata/doom/maps/anthologies/2019 - 1000 Lines.zip"

# Maybe later
# IWAD=doom_fusion.ipk3 MAPS="E1M1 E2M1 E3M1 E4M1 MAP01 TN_MAP01 PL_MAP01" tools/ap-scan "WadFusion"
# MAPS=E1A1 tools/ap-scan "The Adventures of Square" testdata/doom/maps/conversions/2018\ -\ The\ Adventures\ of\ Square\ 1+2.pk3
# IWAD=heretic.wad MAPS="$(echo E1M{1..9})" tools/ap-scan "Faithless" testdata/doom/maps/conversions/2024\ -\ Faithless\ Trilogy\ RC1a.pk3
# tools/ap-scan "Necromantic Thirst" testdata/doom/maps/megawads/2024\ -\ Necromantic\ Thirst\ RC2.zip
# tools/ap-scan "Doom 2 In City Only" testdata/doom/maps/anthologies/2024\ -\ Doom\ 2\ In\ City\ Only.zip
# tools/ap-scan "Eviternity 2" testdata/doom/maps/megawads/2024\ -\ Eviternity\ 2.zip
# tools/ap-scan "Eviternity" testdata/doom/maps/megawads/2019\ -\ Eviternity.zip
