#!/usr/bin/env zsh
#
# Rebuild all of the logic files from scratch.
# This makes a bunch of assumptions about where the maps are stored that are only
# valid on my computer.

IWAD=doom.wad MAPS="E1M1 E2M1 E3M1 E4M1" tools/ap-scan "Doom"
tools/ap-scan "Doom 2"
IWAD=plutonia.wad tools/ap-scan "Plutonia"
IWAD=tnt.wad tools/ap-scan "TNT"
IWAD=freedoom1.wad MAPS="E1M1 E2M1 E3M1 E4M1" tools/ap-scan "FreeDoom"
IWAD=freedoom2.wad tools/ap-scan "FreeDoom 2"
IWAD=heretic.wad MAPS="E1M1 E2M1 E3M1 E4M1 E5M1" tools/ap-scan "Heretic"
IWAD=chex3.wad MAPS="E1M1 E2M1 E3M1" tools/ap-scan "Chex Quest 3"

tools/ap-scan "Demonfear" "testdata/doom/maps/megawads/2000 - Demonfear.zip"
tools/ap-scan "Scythe" "testdata/doom/maps/megawads/2003 - Scythe.zip"
tools/ap-scan "MAYhem 2048" "testdata/doom/maps/anthologies/2014 - MAYhem 2048.wad"
tools/ap-scan "Going Down Turbo" "testdata/doom/maps/megawads/2025 - Going Down Turbo.zip"
tools/ap-scan "1000 Lines" "testdata/doom/maps/anthologies/2019 - 1000 Lines.zip"
SKIP="MAP31 MAP32" tools/ap-scan "1000 Lines II" "testdata/doom/maps/anthologies/2020 - 1000 Lines 2.zip"
MAPS="E1A1 E2A1" SKIP="E1END E2END E2END2" tools/ap-scan \
  "The Adventures of Square" "testdata/doom/maps/conversions/2018 - The Adventures of Square 1+2.pk3"
# MAPS="MAP33 MAP45 MAP60 MAP63 MAP69" PRUNE="MAP31 MAP32" tools/ap-scan \
#   "Space Cats Saga" "testdata/doom/maps/conversions/2024 - Space Cats Saga 1.41.wad"

# Maybe later
# IWAD=doom_fusion.ipk3 MAPS="E1M1 E2M1 E3M1 E4M1 MAP01 TN_MAP01 PL_MAP01" tools/ap-scan "WadFusion"
# IWAD=heretic.wad MAPS="$(echo E1M{1..9})" tools/ap-scan "Faithless" testdata/doom/maps/conversions/2024\ -\ Faithless\ Trilogy\ RC1a.pk3
# tools/ap-scan "Necromantic Thirst" testdata/doom/maps/megawads/2024\ -\ Necromantic\ Thirst\ RC2.zip
# tools/ap-scan "Doom 2 In City Only" testdata/doom/maps/anthologies/2024\ -\ Doom\ 2\ In\ City\ Only.zip
# tools/ap-scan "Eviternity 2" testdata/doom/maps/megawads/2024\ -\ Eviternity\ 2.zip
# tools/ap-scan "Eviternity" testdata/doom/maps/megawads/2019\ -\ Eviternity.zip
