#!/usr/bin/env bash

set -e -x

IWAD="${IWAD:-doom2.wad}"

name="$1"; shift
TMPFILE="tmp/${name}.logic"

autoexec=""
if [[ $MAPS ]]; then
  autoexec="$autoexec ap_scan_levels \"${MAPS}\";"
fi
if [[ $SKIP ]]; then
  autoexec="$autoexec ap_scan_skip \"${SKIP}\";"
fi
if [[ $PRUNE ]]; then
  autoexec="$autoexec ap_scan_prune \"${PRUNE}\";"
fi

make
gzdoom \
  -iwad /ancilla/installs/games/PC/DOOM/IWAD/${IWAD} \
  -file release/gzArchipelago-latest.pk3 \
  "$@" \
  -warp 1 -nomusic \
  +"logfile \"$TMPFILE\"; disableautosave 1; wipetype 0; wait 1; noclip; $autoexec netevent ap-scan:start"

sed -E -i -n '/^AP-/ p;' "$TMPFILE"
for dir in gzap/apworld/gzdoom/logic/ gzap/apworld/addons/*; do
  if [[ -f "${dir}/${name}" ]]; then
    mv -v "$TMPFILE" "${dir}/${name}"
    exit 0
  fi
done

mv -v "$TMPFILE" ~/.local/share/Archipelago/gzdoom/logic/"${name}"
