#!/usr/bin/env bash

set -e -x

SKILL="${SKILL:-2}"  # HNTR
IWAD="${IWAD:-doom2.wad}"
MAPS="${MAPS:-MAP01}"

name="$1"; shift

make
gzdoom \
  -iwad /ancilla/installs/games/PC/DOOM/IWAD/${IWAD} \
  -file release/gzArchipelago-latest.pk3 \
  "$@" \
  -warp 1 \
  -skill $SKILL \
  +"logfile \"gzap/apworld/gzdoom/logic/${name}.tmp\"; disableautosave 1; wipetype 0; wait 1; noclip; ap_scan_levels \"${MAPS}\"; netevent ap-scan:start"

sed -E -i -n '/^AP-/ p;' "gzap/apworld/gzdoom/logic/${name}.tmp"
mv "gzap/apworld/gzdoom/logic/${name}.tmp" "gzap/apworld/gzdoom/logic/${name}"
