#include "./BaseUpgrade.zsc"
#include "./Dot.zsc"
#include "./Registry.zsc"
#include "./UpgradeBag.zsc"

#include "./Explosive.zsc"
#include "./HomingShots.zsc"
#include "./Fire.zsc"
#include "./Leech.zsc"
#include "./Melee.zsc"
#include "./Poison.zsc"
#include "./Simpleupgrades.zsc"
